version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      # install dependencies in both apps
      - run :
          name: install fronend 
          command: | 
              npm run frontend:install
      - run :
          name: install backend 
          command: | 
              npm run backend:install
      - run:
          name: build frontend 
          command: |
              npm run frontend:build
      - run : 
          name: build server side 
          command: | 
              npm run frontend:deploy
      - run :
          name : DEPLOY THE APPLICATION  
          command : | 
              npm run frontend:deploy
     
